In [47]:
import os
from dotenv import load_dotenv
import requests
import json
from datetime import datetime, timedelta
import pandas as pd
import time

load_dotenv()

True

In [48]:
#vehicle count data
url = "https://data.cityofnewyork.us/resource/7ym2-wayt.json"
#      https://data.cityofnewyork.us/resource/btm5-ppia.json
limit = 100000
max_rows = 1712605
offset = 0
traffic_df = pd.DataFrame()
nyc_token = os.getenv("TRAFFIC_KEY")

In [ ]:
while offset < max_rows:
    this_url = url + f"?$limit={limit}&$offset={offset}&$order=:id&$$app_token={nyc_token}"
    print(this_url)
    response = requests.get(this_url)
    if response.status_code == 200:
        json_data = response.json()
        temp_df = pd.DataFrame(json_data)

        print(f"Temp Length {len(temp_df)}")

        print(temp_df.columns)

        #drop pre 2020 data 
        temp_df['yr'] = temp_df['yr'].astype(int)
        temp_df = temp_df[temp_df['yr'] >= 2020]

        #filter only manhatan
        temp_df = temp_df[temp_df['boro'].str.lower() == 'manhattan']

        print(f"Temp Length after cutoff {len(temp_df)}")
        traffic_df = pd.concat([traffic_df, temp_df])
        
    else:
        print(f"Error: {response.status_code}")
    offset = offset + limit
    print(f"Total len {len(traffic_df)}")
    time.sleep(1)

https://data.cityofnewyork.us/resource/7ym2-wayt.json?$limit=100000&$offset=0&$order=:id&$$app_token=wwBwMlUXanS8k91CYV0vJ3NlT
Temp Length 100000
Index(['requestid', 'boro', 'yr', 'm', 'd', 'hh', 'mm', 'vol', 'segmentid',
       'wktgeom', 'street', 'fromst', 'tost', 'direction'],
      dtype='object')
Temp Length after cutoff 2995
Total len 2995
https://data.cityofnewyork.us/resource/7ym2-wayt.json?$limit=100000&$offset=100000&$order=:id&$$app_token=wwBwMlUXanS8k91CYV0vJ3NlT
Temp Length 100000
Index(['requestid', 'boro', 'yr', 'm', 'd', 'hh', 'mm', 'vol', 'segmentid',
       'wktgeom', 'street', 'fromst', 'tost', 'direction'],
      dtype='object')
Temp Length after cutoff 2346
Total len 5341
https://data.cityofnewyork.us/resource/7ym2-wayt.json?$limit=100000&$offset=200000&$order=:id&$$app_token=wwBwMlUXanS8k91CYV0vJ3NlT
Temp Length 100000
Index(['requestid', 'boro', 'yr', 'm', 'd', 'hh', 'mm', 'vol', 'segmentid',
       'wktgeom', 'street', 'fromst', 'tost', 'direction'],
      dtype='object')
Temp Length after cutoff 2266
Total len 7607
https://data.cityofnewyork.us/resource/7ym2-wayt.json?$limit=100000&$offset=300000&$order=:id&$$app_token=wwBwMlUXanS8k91CYV0vJ3NlT
Temp Length 100000
Index(['requestid', 'boro', 'yr', 'm', 'd', 'hh', 'mm', 'vol', 'segmentid',
       'wktgeom', 'street', 'fromst', 'tost', 'direction'],
      dtype='object')
Temp Length after cutoff 4368
Total len 11975
https://data.cityofnewyork.us/resource/7ym2-wayt.json?$limit=100000&$offset=400000&$order=:id&$$app_token=wwBwMlUXanS8k91CYV0vJ3NlT
Temp Length 100000
Index(['requestid', 'boro', 'yr', 'm', 'd', 'hh', 'mm', 'vol', 'segmentid',
       'wktgeom', 'street', 'fromst', 'tost', 'direction'],
      dtype='object')
Temp Length after cutoff 1564
Total len 13539
https://data.cityofnewyork.us/resource/7ym2-wayt.json?$limit=100000&$offset=500000&$order=:id&$$app_token=wwBwMlUXanS8k91CYV0vJ3NlT
Temp Length 100000
Index(['requestid', 'boro', 'yr', 'm', 'd', 'hh', 'mm', 'vol', 'segmentid',
       'wktgeom', 'street', 'fromst', 'tost', 'direction'],
      dtype='object')
Temp Length after cutoff 3222
Total len 16761
https://data.cityofnewyork.us/resource/7ym2-wayt.json?$limit=100000&$offset=600000&$order=:id&$$app_token=wwBwMlUXanS8k91CYV0vJ3NlT
Temp Length 100000
Index(['requestid', 'boro', 'yr', 'm', 'd', 'hh', 'mm', 'vol', 'segmentid',
       'wktgeom', 'street', 'fromst', 'tost', 'direction'],
      dtype='object')
Temp Length after cutoff 1832
Total len 18593
https://data.cityofnewyork.us/resource/7ym2-wayt.json?$limit=100000&$offset=700000&$order=:id&$$app_token=wwBwMlUXanS8k91CYV0vJ3NlT
Temp Length 100000
Index(['requestid', 'boro', 'yr', 'm', 'd', 'hh', 'mm', 'vol', 'segmentid',
       'wktgeom', 'street', 'fromst', 'tost', 'direction'],
      dtype='object')
Temp Length after cutoff 365
Total len 18958
https://data.cityofnewyork.us/resource/7ym2-wayt.json?$limit=100000&$offset=800000&$order=:id&$$app_token=wwBwMlUXanS8k91CYV0vJ3NlT
Temp Length 100000
Index(['requestid', 'boro', 'yr', 'm', 'd', 'hh', 'mm', 'vol', 'segmentid',
       'wktgeom', 'street', 'fromst', 'tost', 'direction'],
      dtype='object')
Temp Length after cutoff 2533
Total len 21491
https://data.cityofnewyork.us/resource/7ym2-wayt.json?$limit=100000&$offset=900000&$order=:id&$$app_token=wwBwMlUXanS8k91CYV0vJ3NlT
Temp Length 100000
Index(['requestid', 'boro', 'yr', 'm', 'd', 'hh', 'mm', 'vol', 'segmentid',
       'wktgeom', 'street', 'fromst', 'tost', 'direction'],
      dtype='object')
Temp Length after cutoff 3046
Total len 24537
https://data.cityofnewyork.us/resource/7ym2-wayt.json?$limit=100000&$offset=1000000&$order=:id&$$app_token=wwBwMlUXanS8k91CYV0vJ3NlT
Temp Length 100000
Index(['requestid', 'boro', 'yr', 'm', 'd', 'hh', 'mm', 'vol', 'segmentid',
       'wktgeom', 'street', 'fromst', 'tost', 'direction'],
      dtype='object')
Temp Length after cutoff 6290
Total len 30827
https://data.cityofnewyork.us/resource/7ym2-wayt.json?$limit=100000&$offset=1100000&$order=:id&$$app_token=wwBwMlUXanS8k91CYV0vJ3NlT
Temp Length 100000
Index(['requestid', 'boro', 'yr', 'm', 'd', 'hh', 'mm', 'vol', 'segmentid',
       'wktgeom', 'street', 'fromst', 'tost', 'direction'],
      dtype='object')
Temp Length after cutoff 6084
Total len 36911
https://data.cityofnewyork.us/resource/7ym2-wayt.json?$limit=100000&$offset=1200000&$order=:id&$$app_token=wwBwMlUXanS8k91CYV0vJ3NlT
Temp Length 100000
Index(['requestid', 'boro', 'yr', 'm', 'd', 'hh', 'mm', 'vol', 'segmentid',
       'wktgeom', 'street', 'fromst', 'tost', 'direction'],
      dtype='object')
Temp Length after cutoff 1761
Total len 38672
https://data.cityofnewyork.us/resource/7ym2-wayt.json?$limit=100000&$offset=1300000&$order=:id&$$app_token=wwBwMlUXanS8k91CYV0vJ3NlT
Temp Length 100000
Index(['requestid', 'boro', 'yr', 'm', 'd', 'hh', 'mm', 'vol', 'segmentid',
       'wktgeom', 'street', 'fromst', 'tost', 'direction'],
      dtype='object')
Temp Length after cutoff 5159
Total len 43831
https://data.cityofnewyork.us/resource/7ym2-wayt.json?$limit=100000&$offset=1400000&$order=:id&$$app_token=wwBwMlUXanS8k91CYV0vJ3NlT
Temp Length 100000
Index(['requestid', 'boro', 'yr', 'm', 'd', 'hh', 'mm', 'vol', 'segmentid',
       'wktgeom', 'street', 'fromst', 'tost', 'direction'],
      dtype='object')
Temp Length after cutoff 7363
Total len 51194
https://data.cityofnewyork.us/resource/7ym2-wayt.json?$limit=100000&$offset=1500000&$order=:id&$$app_token=wwBwMlUXanS8k91CYV0vJ3NlT
Temp Length 100000
Index(['requestid', 'boro', 'yr', 'm', 'd', 'hh', 'mm', 'vol', 'segmentid',
       'wktgeom', 'street', 'fromst', 'tost', 'direction'],
      dtype='object')
Temp Length after cutoff 1043
Total len 52237
https://data.cityofnewyork.us/resource/7ym2-wayt.json?$limit=100000&$offset=1600000&$order=:id&$$app_token=wwBwMlUXanS8k91CYV0vJ3NlT
Temp Length 100000
Index(['requestid', 'boro', 'yr', 'm', 'd', 'hh', 'mm', 'vol', 'segmentid',
       'wktgeom', 'street', 'fromst', 'tost', 'direction'],
      dtype='object')
Temp Length after cutoff 3321
Total len 55558
https://data.cityofnewyork.us/resource/7ym2-wayt.json?$limit=100000&$offset=1700000&$order=:id&$$app_token=wwBwMlUXanS8k91CYV0vJ3NlT
Temp Length 12605
Index(['requestid', 'boro', 'yr', 'm', 'd', 'hh', 'mm', 'vol', 'segmentid',
       'wktgeom', 'street', 'fromst', 'tost', 'direction'],
      dtype='object')
Temp Length after cutoff 51
Total len 55609

In [50]:
len(traffic_df)
#313934

55609

In [51]:
traffic_df['boro'].unique()
traffic_df['yr'].unique()

array([2020, 2023, 2021, 2022, 2024])

In [52]:
traffic_df.head()

,requestid,boro,yr,m,d,hh,mm,vol,segmentid,wktgeom,street,fromst,tost,direction
1121,32440,Manhattan,2020,11,8,20,45,62,72596,POINT (1004612.5006665062 254120.7358176789),DYCKMAN STREET,Sherman Avenue,Vermilyea Avenue,NB
1122,32440,Manhattan,2020,11,8,21,0,63,72596,POINT (1004612.5006665062 254120.7358176789),DYCKMAN STREET,Sherman Avenue,Vermilyea Avenue,NB
1123,32440,Manhattan,2020,11,8,21,15,43,72596,POINT (1004612.5006665062 254120.7358176789),DYCKMAN STREET,Sherman Avenue,Vermilyea Avenue,NB
1124,32440,Manhattan,2020,11,8,21,30,46,72596,POINT (1004612.5006665062 254120.7358176789),DYCKMAN STREET,Sherman Avenue,Vermilyea Avenue,NB
1125,32440,Manhattan,2020,11,8,21,45,36,72596,POINT (1004612.5006665062 254120.7358176789),DYCKMAN STREET,Sherman Avenue,Vermilyea Avenue,NB

In [53]:
traffic_df['date'] = traffic_df['yr'].astype(str) + "-" + traffic_df['m'].astype(str) + "-" + traffic_df['d'].astype(str)
#df['new_col'] = df['col1'].astype(str) + '-' + df['col2'].astype(str) + '-' + df['col3'].astype(str)
traffic_df['date'] = pd.to_datetime(traffic_df['date'])
traffic_df.head()

,requestid,boro,yr,m,d,hh,mm,vol,segmentid,wktgeom,street,fromst,tost,direction,date
1121,32440,Manhattan,2020,11,8,20,45,62,72596,POINT (1004612.5006665062 254120.7358176789),DYCKMAN STREET,Sherman Avenue,Vermilyea Avenue,NB,2020-11-08
1122,32440,Manhattan,2020,11,8,21,0,63,72596,POINT (1004612.5006665062 254120.7358176789),DYCKMAN STREET,Sherman Avenue,Vermilyea Avenue,NB,2020-11-08
1123,32440,Manhattan,2020,11,8,21,15,43,72596,POINT (1004612.5006665062 254120.7358176789),DYCKMAN STREET,Sherman Avenue,Vermilyea Avenue,NB,2020-11-08
1124,32440,Manhattan,2020,11,8,21,30,46,72596,POINT (1004612.5006665062 254120.7358176789),DYCKMAN STREET,Sherman Avenue,Vermilyea Avenue,NB,2020-11-08
1125,32440,Manhattan,2020,11,8,21,45,36,72596,POINT (1004612.5006665062 254120.7358176789),DYCKMAN STREET,Sherman Avenue,Vermilyea Avenue,NB,2020-11-08

In [54]:
traffic_df['vol'] = traffic_df['vol'].astype(int)

traffic_df = traffic_df.groupby('date', as_index=False)['vol'].sum()

In [60]:
traffic_df.sort_values(by='date').to_csv('traffic.csv')